#-------------------------------
# General Site Settings

title: MALIK EHSAN
description: WELCOME TO MY WEBSITE
email: contact@malikehsan.com

# NOTE: The Logo and Background image are defined in the all.sass document.

menu:
- {name: About me, url: '#about-me'}
- {name: Projects, url: '#work'}
- {name: Extracurricular, url: '#clients'}
- {name: Blog, url: '#blog'}
- {name: Contact, url: '#contact'}


#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'Malik Ehsan, Carleton University, Computer Science, web developer, software engineering'
  rel-author: 'Malik Ehsan'
  rel-publisher: 'Malik Ehsan'

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

#google-analytics-ua: UA-XXXXXX-X

#-------------------------------
# About Section

# NOTE: The avatar is defined in the all.sass document.


#-------------------------------
# Work Section

projects:
- {name: COMP3004 Software Engineering Project, folder: 'proj-1', file: 'work/proj-1.html'}
- {name: Comp3000 HAcK THE OS , folder: 'proj-2', file: 'work/proj-2.html'}
- {name: comp3008 HUD system prototype, folder: 'proj-3', file: 'work/proj-3.html'}
- {name: comp4004 class registration system, folder: 'proj-4', file: 'work/proj-4.html'}
- {name: android App, folder: 'proj-5', file: 'work/proj-5.html'}
- {name: Various Design Projects, folder: 'proj-6', file: 'work/proj-6.html'}





#-------------------------------
# Clients Section

clients:
- {
  name: 'Canadian Cancer Society',
  title: 'Creative Director (2014-2015)',
  quote: <ul>
  <li>Created Posters </li>
  <li>Worked hard</li>
  <li>Made marketting decisions</li>
  <li>Worked vigourously to collect donations </li>
   <li>Designed posters for the fundrasing</li>
</ul>,
  logo: 'logo1.png'}
- {avatar: 'face-atariboy.jpg',
  name: 'Paul Menton Centre (Carleton University)',
  title: 'Volunteer Notetaker 2015-2017',
  quote: <ul>
  <li>Created Posters </li>
  <li>Worked hard</li>
  <li>Made marketting decisions</li>
  <li>Worked vigourously to collect donations </li>
   <li>Designed posters for the fundrasing</li>
</ul>,
  logo: 'logo2.png'}
- {avatar: 'face-jackiesaik.jpg',
  name: 'Humans of Carleton',
  title: 'Digital Media Executive 2015-2016',
  quote: <ul>
  <li>Created Posters </li>
  <li>Worked hard</li>
  <li>Made marketting decisions</li>
  <li>Worked vigourously to collect donations </li>
   <li>Designed posters for the fundrasing</li>
</ul>,  
  logo: 'logo3.png'}
- {avatar: 'face-teleject.jpg',
  name: 'Various Clubs at Carleton',
  title: 'Web Developer / Graphic Designer',
   quote: <ul>
  <li>Created Posters </li>
  <li>Worked hard</li>
  <li>Made marketting decisions</li>
  <li>Worked vigourously to collect donations </li>
   <li>Designed posters for the fundrasing</li>
</ul>,  
  logo: 'logo4.png'}


#-------------------------------
# Contact Section

social:
- {icon: 'github', link: ''}
- {icon: 'linkedin', link: ''}


# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'
